# Generated by Django 4.2.13 on 2024-06-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('can_manage_categories', 'Can manage categories')]},
        ),
    ]
